const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const context = { console, fetch: async () => { throw new Error('fetch is not used in this test'); }, XLSX: null };
vm.createContext(context);
vm.runInContext(fs.readFileSync('js/database.js', 'utf8'), context);
const publishedRaw = JSON.parse(fs.readFileSync('database/persona-db.json', 'utf8'));
context.applyRawDatabase(publishedRaw, {source: 'bundled', filename: 'database/persona-db.json'});
context.startEditingSession();
const original = context.activeDatabaseSnapshot()['05_Personas'][0].PersonaName;
const first = context.activeDatabaseSnapshot();
first['05_Personas'][0].PersonaName = `${original} history`;
context.updateWorkingCopy(first, 'persona-save');
assert.strictEqual(context.canUndoEdit(), true);
assert.strictEqual(context.editingChangeList().some(c => c.kind === 'modified field' && c.before === original && c.after === `${original} history`), true);
context.undoLastEdit();
assert.strictEqual(context.databaseState().personas[0].PersonaName, original);
assert.strictEqual(context.canRedoEdit(), true);
context.redoLastEdit();
assert.strictEqual(context.databaseState().personas[0].PersonaName, `${original} history`);
context.undoLastEdit();
const divergent = context.activeDatabaseSnapshot();
divergent['05_Personas'][0].PersonaName = `${original} divergent`;
context.updateWorkingCopy(divergent, 'persona-save');
assert.strictEqual(context.canRedoEdit(), false, 'new divergent edit clears redo stack');
const change = context.editingChangeList().find(c => c.field === 'PersonaName');
assert(change, 'change list includes modified field');
context.discardUncommittedChange(change.id);
assert.strictEqual(context.databaseState().personas[0].PersonaName, original, 'individual safe discard restores field');
assert.strictEqual(context.publishedDatabaseSnapshot()['05_Personas'][0].PersonaName, original, 'published database remains preserved');
console.log('Change history supports undo, redo, divergent redo clearing, review diffs, and safe individual discard.');
